version: '3.1'

services:
  db:
    image: mysql:8.0.28
    restart: always
    environment:
      MYSQL_DATABASE: 'super-app'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - "3306:3306"

  node-app:
    build:
      context: C:\Users\gavri\Desktop\Devops project\super-app\node
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - db

  php-app:
    build:
      context: C:\Users\gavri\Desktop\Devops project\super-app\php
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - db